### PR TITLE
Don't crash while trying to parse a diff for binary files, fix #128

### LINKED ISSUE #128: Error when sync an empty file
**🐞 Describe the bug**

When synchronize a file which is empty I have the following errors :

Synchronize Files
Cannot read property 'startsWith' of undefined

Synchronize Files
TypeError: Cannot read property 'startsWith' of undefined

**📚 To Reproduce**

Create a file with no content.
I created an empty docker-compose.yaml file 

**💡 Expected behavior**

I expected to have my file syncronized

**🖼️ Screenshots**

**⚙️ Environment**
- Action version: [e.g. v1.0.0]

**📋 Additional context**

### PR DESCRIPTION
**Pull request by exAspArk**
image

> Error: Cannot read property 'startsWith' of undefined

Config:

```yml
bar/foo@master:
  - test.txt
```

To reproduce, change a binary file (e.g., `*.gz`) in a commit with `test.txt` and try to sync it

Fixes https://github.com/BetaHuhn/repo-file-sync-action/issues/128

### CODE REVIEW

File: src/git.js [hunk 1]
```diff
@@ -159,6 +159,8 @@ class Git {
 		// split diff into separate entries for separate files. \ndiff --git should be a reliable way to detect the separation, as content of files is always indented
 		return `\n${ string }`.split('\ndiff --git').slice(1).reduce((resultDict, fileDiff) => {
 			const lines = fileDiff.split('\n')
+			if (lines.length === 0) return resultDict; // ignore binary files
```
Comment (exAspArk) [inline src/git.js:162]: I'm not sure if it's the best way to fix it in the long term. But I hope this will at least prevent from crashing halfway and not syncing all files

Comment (exAspArk) [inline src/git.js:162]: I'm not sure if it's the best way to fix it in the long term. But I hope this will at least prevent from crashing halfway and not syncing all files. Please let me know what you think

**Review by BetaHuhn — APPROVED** [review]
